server:
  port: 8333
#  context-path: /eureka
eureka:
#  instance:
#    hostname: tianwen1
  client:
    service-url:
#      defaultZone: http://tianwen2:8444/eureka
      defaultZone: http://127.0.0.1:8444/eureka,http://127.0.0.1:8445/eureka
    register-with-eureka: false
    fetch-registry: false

logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF